# mongo-secret.yaml for the database namespace
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: webapp
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
